{{- if .Values.useTensorboard }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tensorboard
  labels:
    app: {{ .Values.trainingType }}
    chart: {{ template "etjob.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: tensorboard
    createdBy: {{ .Values.trainingType }}
spec:
  type: {{ .Values.tensorboardServiceType }}
  ports:
    - port: 6006
      targetPort: 6006
      protocol: TCP
      name: tensorboard
  selector:
    app: {{ .Values.trainingType }}
    chart: {{ template "etjob.chart" . }}
    release: {{ .Release.Name }}
    role: tensorboard
{{- end }}
