#!/command/with-contenv bash
CONTENT="#!/bin/bash\n\nssh root@${SSH_HOST} -p ${SSH_PORT} -i id_rsa"

# check if /root/.ssh/id_rsa exists
if [ ! -f /root/.ssh/id_rsa ]; then
    ssh-keygen -t rsa -N "" -f /root/.ssh/id_rsa
    echo "SSH key pair created at /root/.ssh/id_rsa"
    cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
fi

# check if /root/ssh-tool exists
if [ ! -d /root/ssh-tool ]; then
    mkdir -p /root/ssh-tool
fi

# fix ssh permission
chmod 700 /root/.ssh
chmod 600 /root/.ssh/authorized_keys

# force to update ssh config
cp /root/.ssh/id_rsa /root/ssh-tool

# force to update ssh connection script
echo -e ${CONTENT} > /root/ssh-tool/connect.sh
chmod +x /root/ssh-tool/connect.sh

# pack ssh-tool
rm -f /root/ssh-tool/ssh-tool.tar.gz
tar -czvf /root/ssh-tool.tar.gz -C /root/ssh-tool
mv /root/ssh-tool.tar.gz /root/ssh-tool

# start ssh service
service ssh start
