name: Docker Image Pull

on:
  push:
    branches: [ "main" ]
    paths: [
      ".github/workflows/docker_pull.yml",
    ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, closed]
    paths: [
      ".github/workflows/docker_pull.yml",
    ]

env:
  VERSION: 3.1.0

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action != 'closed' }}
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache
#    - name: Pull Docker images
#      run: docker pull gcr.io/ml-pipeline/cache-server:2.0.5
#    - name: Tag Docker images
#      run: docker tag gcr.io/ml-pipeline/cache-server:2.0.5 saz0568/zelos-image:ml-pipeline_cache-server_2.0.5
#    - name: Push Docker images
#      run: docker push saz0568/zelos-image:ml-pipeline_cache-server_2.0.5
#    - name: Pull Docker images
#      run: docker pull gcr.io/ml-pipeline/metadata-envoy:2.0.5
#    - name: Tag Docker images
#      run: docker tag gcr.io/ml-pipeline/metadata-envoy:2.0.5 saz0568/zelos-image:ml-pipeline_metadata-envoy_2.0.5
#    - name: Push Docker images
#      run: docker push saz0568/zelos-image:ml-pipeline_metadata-envoy_2.0.5
#    - name: Pull Docker images
#      run: docker pull gcr.io/tfx-oss-public/ml_metadata_store_server:1.14.0
#    - name: Tag Docker images
#      run: docker tag gcr.io/tfx-oss-public/ml_metadata_store_server:1.14.0 saz0568/zelos-image:ml_metadata_store_server_1.14.0
#    - name: Push Docker images
#      run: docker push saz0568/zelos-image:ml_metadata_store_server_1.14.0
#    - name: Pull Docker images
#      run: docker pull gcr.io/ml-pipeline/metadata-writer:2.0.5
#    - name: Tag Docker images
#      run: docker tag gcr.io/ml-pipeline/metadata-writer:2.0.5 saz0568/zelos-image:ml-pipeline_metadata-writer_2.0.5
#    - name: Push Docker images
#      run: docker push saz0568/zelos-image:ml-pipeline_metadata-writer_2.0.5
#    - name: Pull Docker images
#      run: docker pull gcr.io/ml-pipeline/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance
#    - name: Tag Docker images
#      run: docker tag gcr.io/ml-pipeline/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance saz0568/zelos-image:ml-pipeline_minio_RELEASE.2019-08-14T20-37-41Z-license-compliance
#    - name: Push Docker images
#      run: docker push saz0568/zelos-image:ml-pipeline_minio_RELEASE.2019-08-14T20-37-41Z-license-compliance
#    - name: Pull Docker images
#      run: docker pull gcr.io/ml-pipeline/api-server:2.0.5
#    - name: Tag Docker images
#      run: docker tag gcr.io/ml-pipeline/api-server:2.0.5 saz0568/zelos-image:ml-pipeline_api-server_2.0.5
#    - name: Push Docker images
#      run: docker push saz0568/zelos-image:ml-pipeline_api-server_2.0.5
#    - name: Pull Docker images
#      run: docker pull gcr.io/ml-pipeline/persistenceagent:2.0.5
#    - name: Tag Docker images
#      run: docker tag gcr.io/ml-pipeline/persistenceagent:2.0.5 saz0568/zelos-image:ml-pipeline_persistenceagent_2.0.5
#    - name: Push Docker images
#      run: docker push saz0568/zelos-image:ml-pipeline_persistenceagent_2.0.5
#    - name: Pull Docker images
#      run: docker pull gcr.io/ml-pipeline/scheduledworkflow:2.0.5
#    - name: Tag Docker images
#      run: docker tag gcr.io/ml-pipeline/scheduledworkflow:2.0.5 saz0568/zelos-image:ml-pipeline_scheduledworkflow_2.0.5
#    - name: Push Docker images
#      run: docker push saz0568/zelos-image:ml-pipeline_scheduledworkflow_2.0.5
#    - name: Pull Docker images
#      run: docker pull gcr.io/ml-pipeline/frontend:2.0.5
#    - name: Tag Docker images
#      run: docker tag gcr.io/ml-pipeline/frontend:2.0.5 saz0568/zelos-image:ml-pipeline_frontend_2.0.5
#    - name: Push Docker images
#      run: docker push saz0568/zelos-image:ml-pipeline_frontend_2.0.5
#    - name: Pull Docker images
#      run: docker pull gcr.io/ml-pipeline/viewer-crd-controller:2.0.5
#    - name: Tag Docker images
#      run: docker tag gcr.io/ml-pipeline/viewer-crd-controller:2.0.5 saz0568/zelos-image:ml-pipeline_viewer-crd-controller_2.0.5
#    - name: Push Docker images
#      run: docker push saz0568/zelos-image:ml-pipeline_viewer-crd-controller_2.0.5
#    - name: Pull Docker images
#      run: docker pull gcr.io/ml-pipeline/visualization-server:2.0.5
#    - name: Tag Docker images
#      run: docker tag gcr.io/ml-pipeline/visualization-server:2.0.5 saz0568/zelos-image:ml-pipeline_visualization-server_2.0.5
#    - name: Push Docker images
#      run: docker push saz0568/zelos-image:ml-pipeline_visualization-server_2.0.5
#    - name: Pull Docker images
#      run: docker pull gcr.io/ml-pipeline/mysql:8.0.26
#    - name: Tag Docker images
#      run: docker tag gcr.io/ml-pipeline/mysql:8.0.26 saz0568/zelos-image:ml-pipeline_mysql_8.0.26
#    - name: Push Docker images
#      run: docker push saz0568/zelos-image:ml-pipeline_mysql_8.0.26
#    - name: Pull Docker images
#      run: docker pull gcr.io/ml-pipeline/workflow-controller:v3.3.10-license-compliance
#    - name: Tag Docker images
#      run: docker tag gcr.io/ml-pipeline/workflow-controller:v3.3.10-license-compliance saz0568/zelos-image:ml-pipeline_workflow-controller_v3.3.10-license-compliance
#    - name: Push Docker images
#      run: docker push saz0568/zelos-image:ml-pipeline_workflow-controller_v3.3.10-license-compliance
#     - name: Pull Docker images
#       run: docker pull gcr.io/ml-pipeline/argoexec:v3.3.10-license-compliance
#     - name: Tag Docker images
#       run: docker tag gcr.io/ml-pipeline/argoexec:v3.3.10-license-compliance saz0568/zelos-image:ml-pipeline_argoexec_v3.3.10-license-compliance
#     - name: Push Docker images
#       run: docker push saz0568/zelos-image:ml-pipeline_argoexec_v3.3.10-license-compliance
#     - name: Pull Docker images
#       run: docker pull gcr.io/ml-pipeline/kfp-driver@sha256:8e60086b04d92b657898a310ca9757631d58547e76bbbb8bfc376d654bef1707
#     - name: Tag Docker images
#       run: docker tag gcr.io/ml-pipeline/kfp-driver@sha256:8e60086b04d92b657898a310ca9757631d58547e76bbbb8bfc376d654bef1707 saz0568/zelos-image:ml-pipeline_kfp-driver_sha256-8e60086b04d92b657898a310ca9757631d58547e76bbbb8bfc376d654bef1707
#     - name: Push Docker images
#       run: docker push saz0568/zelos-image:ml-pipeline_kfp-driver_sha256-8e60086b04d92b657898a310ca9757631d58547e76bbbb8bfc376d654bef1707
#    - name: Pull Docker images
#      run: docker pull python:3.8.19
#    - name: Tag Docker images
#      run: docker tag python:3.8.19 saz0568/zelos-image:python-3.8.19
#    - name: Push Docker images
#      run: docker push saz0568/zelos-image:python-3.8.19
    - name: Pull Docker images
      run: docker pull redis/redis-stack:7.4.0-v0
    - name: Tag Docker images
      run: docker tag redis/redis-stack:7.4.0-v0 saz0568/zelos-image:redis-stack-7.4.0-v0
    - name: Push Docker images
      run: docker push saz0568/zelos-image:redis-stack-7.4.0-v0
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache
    - name: Pull Docker image from DockerHub
      run: docker pull saz0568/zelos-image:redis-stack-7.4.0-v0
      #    - name: Pull Docker image from DockerHub
      #      run: docker pull saz0568/zelos-image:python-3.8.19
#        docker pull saz0568/zelos-image:ml-pipeline_argoexec_v3.3.10-license-compliance
#        docker pull saz0568/zelos-image:ml-pipeline_cache-server_2.0.5 && 
#        docker pull saz0568/zelos-image:ml-pipeline_metadata-envoy_2.0.5 && 
#        docker pull saz0568/zelos-image:ml_metadata_store_server_1.14.0 && 
#        docker pull saz0568/zelos-image:ml-pipeline_metadata-writer_2.0.5 && 
#        docker pull saz0568/zelos-image:ml-pipeline_minio_RELEASE.2019-08-14T20-37-41Z-license-compliance && 
#        docker pull saz0568/zelos-image:ml-pipeline_api-server_2.0.5 && 
#        docker pull saz0568/zelos-image:ml-pipeline_persistenceagent_2.0.5 && 
#        docker pull saz0568/zelos-image:ml-pipeline_scheduledworkflow_2.0.5 && 
#        docker pull saz0568/zelos-image:ml-pipeline_frontend_2.0.5 && 
#        docker pull saz0568/zelos-image:ml-pipeline_viewer-crd-controller_2.0.5 && 
#        docker pull saz0568/zelos-image:ml-pipeline_visualization-server_2.0.5 && 
#        docker pull saz0568/zelos-image:ml-pipeline_mysql_8.0.26 && 
#        docker pull saz0568/zelos-image:ml-pipeline_workflow-controller_v3.3.10-license-compliance
    - name: Log in to zelos Harbor
      run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login harbor.zelostech.com.cn:5443 --username=${{ secrets.HARBOR_USERNAME }} --password-stdin
    - name: Tag Harbor images
      run: docker tag saz0568/zelos-image:redis-stack-7.4.0-v0 harbor.zelostech.com.cn:5443/devops/redis/redis-stack:7.4.0-v0
#        docker tag saz0568/zelos-image:ml-.3.10-license-compliance harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_argoexec_v3.3.10-license-compliance
#        docker tag saz0568/zelos-image:ml-pipeline_cache-server_2.0.5 harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_cache-server_2.0.5 && 
#        docker tag saz0568/zelos-image:ml-pipeline_metadata-envoy_2.0.5 harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_metadata-envoy_2.0.5 && 
#        docker tag saz0568/zelos-image:ml_metadata_store_server_1.14.0 harbor.zelostech.com.cn:5443/devops/kubeflow:ml_metadata_store_server_1.14.0 && 
#        docker tag saz0568/zelos-image:ml-pipeline_metadata-writer_2.0.5 harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_metadata-writer_2.0.5 && 
#        docker tag saz0568/zelos-image:ml-pipeline_minio_RELEASE.2019-08-14T20-37-41Z-license-compliance harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_minio_RELEASE.2019-08-14T20-37-41Z-license-compliance && 
#        docker tag saz0568/zelos-image:ml-pipeline_api-server_2.0.5 harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_api-server_2.0.5 && 
#        docker tag saz0568/zelos-image:ml-pipeline_persistenceagent_2.0.5 harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_persistenceagent_2.0.5 && 
#        docker tag saz0568/zelos-image:ml-pipeline_scheduledworkflow_2.0.5 harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_scheduledworkflow_2.0.5 && 
#        docker tag saz0568/zelos-image:ml-pipeline_frontend_2.0.5 harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_frontend_2.0.5 && 
#        docker tag saz0568/zelos-image:ml-pipeline_viewer-crd-controller_2.0.5 harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_viewer-crd-controller_2.0.5 && 
#        docker tag saz0568/zelos-image:ml-pipeline_visualization-server_2.0.5 harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_visualization-server_2.0.5 && 
#        docker tag saz0568/zelos-image:ml-pipeline_mysql_8.0.26 harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_mysql_8.0.26 && 
#        docker tag saz0568/zelos-image:ml-pipeline_workflow-controller_v3.3.10-license-compliance harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_workflow-controller_v3.3.10-license-compliance
    - name: Push Harbor images
      run: docker push harbor.zelostech.com.cn:5443/devops/redis/redis-stack:7.4.0-v0
      #    - name: Push Harbor images
      #      run: docker push harbor.zelostech.com.cn:5443/devops/python:3.8.19
#        docker push harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_argoexec_v3.3.10-license-compliance
#        docker push harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_cache-server_2.0.5 && 
#        docker push harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_metadata-envoy_2.0.5 && 
#        docker push harbor.zelostech.com.cn:5443/devops/kubeflow:ml_metadata_store_server_1.14.0 && 
#        docker push harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_metadata-writer_2.0.5 && 
#        docker push harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_minio_RELEASE.2019-08-14T20-37-41Z-license-compliance && 
#        docker push harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_api-server_2.0.5 && 
#        docker push harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_persistenceagent_2.0.5 && 
#        docker push harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_scheduledworkflow_2.0.5 && 
#        docker push harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_frontend_2.0.5 && 
#        docker push harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_viewer-crd-controller_2.0.5 && 
#        docker push harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_visualization-server_2.0.5 && 
#        docker push harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_mysql_8.0.26 && 
#        docker push harbor.zelostech.com.cn:5443/devops/kubeflow:ml-pipeline_workflow-controller_v3.3.10-license-compliance
